---

---

 // Autogenerated arrays of content to populate the featured images at the top of index.html

var topImages = [
  {% for post in site.documents reversed %}
      {% if post.tags contains "featured" %}
        '{{ post.img}}',
      {% endif %}
  {% endfor %}
]

var topImageText = [
  {% for post in site.documents reversed %}
    {% if post.tags contains "featured" %}
      '<span class=\'topImage-emphasis\'>{{post.title}}</span>{% if post.featuredSummary %}: {% endif %}{{post.featuredSummary}}',
    {% endif %}
  {% endfor %}
]

var topImageHref = [
  {% for post in site.documents reversed %}
    {% if post.tags contains "featured" %}
      '{{post.url}}',
    {% endif %}
  {% endfor %}
]

// ------------------------------------------------------------------------------------------

var loader = new PxLoader()

// End globals

for (var i = 0; i < topImages.length; i++) {
  loader.addImage(topImages[i])
}
loader.start()

// Cycles through the arrays of images and captions above
loader.addCompletionListener(function () {
  // Remove the loading animation
  document.getElementById('spinner').style.display = 'none'

  // Show the caption card
  document.getElementById('caption').style.display = 'block'

  // Now loop over all images
  var i = 0

  function nextTopImage () {
    $('#top-overlay').css('opacity', 0)

    $('#top-overlay').css('background-image', 'url(' + topImages[i] + ')')
    $('#top-overlay').animate({opacity: '1'}, 1000, function () {
      document.getElementById('top').style.backgroundImage = 'url(' + topImages[i] + ')'
      i = (i + 1) % topImages.length
    })

    $('.results').html(topImageText[i])
    $('#jumbo-card').attr('href', topImageHref[i])
  }
  nextTopImage()
  setInterval(nextTopImage, 6000)
})
