collections:
  code:
    output: true
    permalink: /projects/code/:path/
  maps:
    output: true
    permalink: /projects/maps/:path/
  web:
    output: true
    permalink: /projects/web/:path/
  misc:
    output: true
    permalink: /projects/misc/:path/
  resume:
    output: true
    permalink: /resume/:path/

permalink: /posts/:categories/:year/:month/:day/:title/
paginate: 4
paginate_path: /posts/page:num/

plugins: [jekyll-paginate]
plugins_dir:
  jekyll-paginate

title: atoft.dev

description: "I'm a games programmer and graduate in Computer Science from the University of Cambridge. This is a collection of my projects including games, web design and mods."

url: "https://atoft.dev"

baseurl: ""

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
#gems:
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
